version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: styled-components
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.7
    - 5.1.8
  - dependency-name: react-icons
    versions:
    - 4.1.0
  - dependency-name: "@types/styled-system"
    versions:
    - 5.1.10
